### ISSUE TITLE
Render the output of this project to DECA

### ISSUE THREAD

**Issue by FortisCK** [evonneng/learning2listen#12]
Hi, @evonneng 
There are 3 keys(exp,pose,prob) in pkl files, but the _decode_ function in DECA needs ['shape', 'tex', 'exp', 'pose', 'cam', 'light'] keys. How to use these three keys to correspond to them?

**Comment by nguyenntt97** [comment]
Not the author myself, but you could use the `demo_transfer.py` in DECA for FLAME 3D rendering.
Just override the `exp` and `pose` features to `id_codedict["pose"]` `id_codedict["exp"]` and used the `decode` function to render. Other params could be inherited from a random image (as we didn't have those params in L2L dataset).
