### ISSUE TITLE
Usage of List of Files

### ISSUE THREAD

**Issue by Daksitha** [evonneng/learning2listen#4]
Hi @evonneng, I was wondering what is the usage of p*_speak_files_clean_deca.npy files?

I am creating my own dataset, therefore, was wondering should I generate a file similar to this for every speaker in my dataset as well? 

If I understood correct, this contains the file path, speaker location and number of frames of a particular speaker, is that correct?

**Comment by evonneng** [comment]
Hi! Thank you for your interest in our paper. 
Your understanding of the *files*.npy is correct! I mainly used them to correspond the processed data with the raw videos. It's not necessary to use during training. Hope that helps!
Best,
Evonne
